import 'package:flutter/material.dart';
import 'package:future_to_provider/widgets/job_list.dart';
// import 'package:future_to_provider/provider/provider_job.dart';
import 'package:future_to_provider/provider/provider_job_details.dart';
import 'package:provider/provider.dart';

import '../widgets/job_detail_list.dart';

//import '../widget/detailscreen.dart';
class JobScreen2 extends StatefulWidget {
  static const routeName = '/JobScreen2';
  @override
  _JobScreen2State createState() => _JobScreen2State();
}

class _JobScreen2State extends State<JobScreen2> {
  var isloading = true;

  @override
  void initState() {
    super.initState();
    Provider.of<PrividerJob2>(context, listen: false)
        .fetchAutogenerated()
        .then((_) {
      setState(() {
        isloading = false;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    final args = ModalRoute.of(context)!.settings.arguments as String;
    // final String s=args.
    print(args);
    final productdata = Provider.of<PrividerJob2>(context, listen: false);
    final products = productdata.list2;
    return Scaffold(
      appBar: AppBar(
        title: Text(args),
      ),
      backgroundColor: Colors.black,
      body: isloading
          ? Center(child: CircularProgressIndicator())
          : ListView.builder(
              itemCount: products.length,
              itemBuilder: (ctx, index) => args == products[index].category
                  ? JobListWidget2(products[index].companyName,
                      products[index].jobType, products[index].title)
                  : Text('',
                      style: TextStyle(
                          
                          fontSize: 0)),
            ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {});
        },
      ),
    );
    //https://picsum.photos/200/300
  }
}
